### ISSUE TITLE
关于你的可编程灯牌

### ISSUE THREAD

**Issue by keyqing5** [QuartzYan/pioneer3at_pkg#2]
看到你在github上的发帖https://github.com/ccyyycy/ycy/issues/39 想问问缺不缺打杂？
不怎么会 但是觉得你的思路很有意思...

**Comment by QuartzYan** [comment]
没问题啊，等我下班，然后拉个群

**Comment by lzz212** [comment]
我做iOS开发的，公司里倒是有这种App和设备交互的项目 可以拉我啊  410791525

**Comment by wangbolocojoy** [comment]
有没有组队的APP

**Comment by Cosin777** [comment]
感觉能做成手机app指挥全部灯牌，变成超大显示屏，貌似只需要再封装一层？。我是做图像算法的，希望能加入。qq527896587

**Comment by keyqing5** [comment]
> 没问题啊，等我下班，然后拉个群

Q 734698404

**Comment by mojunmo1216** [comment]
Q 438364248，安卓程序猿，熟练掌握Socket通信，蓝牙开发~~~

**Comment by fishpisces** [comment]
@QuartzYan 老哥，我跟你的想法类似。有点扩展，issue没法回复了，这里@你看看我的那点想法能不能做~
https://github.com/ccyyycy/ycy/issues/24

**Comment by liux-pro** [comment]
我可以打打杂，平时玩一些nodemcu和micropython Q 946936114

**Comment by wenner** [comment]
> @QuartzYan 老哥，我跟你的想法类似。有点扩展，issue没法回复了，这里@你看看我的那点想法能不能做~
> [ccyyycy/ycy#24](https://github.com/ccyyycy/ycy/issues/24)

如果把灯牌换成手机呢?
这样就不需要其他附件了...
手机作为一个点...是不是更易用些...

实现静态文本和图像应该不难..
只是如何让这些现实同步...

**Comment by fishpisces** [comment]
> 
> 
> > @QuartzYan 老哥，我跟你的想法类似。有点扩展，issue没法回复了，这里@你看看我的那点想法能不能做~
> > [ccyyycy/ycy#24](https://github.com/ccyyycy/ycy/issues/24)
> 
> 如果把灯牌换成手机呢?
> 这样就不需要其他附件了...
> 手机作为一个点...是不是更易用些...
> 
> 实现静态文本和图像应该不难..
> 只是如何让这些现实同步...

手机的话是不难，但是就是手机屏幕太小了……

**Comment by wenner** [comment]
> > > @QuartzYan 老哥，我跟你的想法类似。有点扩展，issue没法回复了，这里@你看看我的那点想法能不能做~
> > > [ccyyycy/ycy#24](https://github.com/ccyyycy/ycy/issues/24)
> > 
> > 
> > 如果把灯牌换成手机呢?
> > 这样就不需要其他附件了...
> > 手机作为一个点...是不是更易用些...
> > 实现静态文本和图像应该不难..
> > 只是如何让这些现实同步...
> 
> 手机的话是不难，但是就是手机屏幕太小了……

我的意思,不是一个手机,而是多部手机,组成一个灯牌....类似无人机那样显示点阵文字和图案
每个手机就类似一个LED点,每个手机事先都标记好自己的位置,然后由服务器将要显示的内容分发到各个手机...然后定时..到时间后同时显示...

我不知道现在有没有这样的东西...我只是觉得这样是可以实现的...
我看新闻说这次广州演唱会会有2100个同学参加...2100个点...比无人机的点多多了,而且应该也比较密集...
应该是可以的,可以做成APP或者小程序,当然小程序实现更快一些,更新也更简单

============
我想是不是可以这样实现
- [管理者] 一次活动前,生成座位图
- [用户] 参加人员选中自己的座位进行标记(类似买电影票)
- [管理者] **根据座位的排布点阵,制作N个显示方案**
  - 显示方案比如就显示"杨超越"三个字进行切换,每个字显示3秒
  - 将文字转成点阵,可以标记到那个点亮,那个点灭,然后几秒后切换文字,再次标记那个点亮那个点灭
  - 整体时间轴下将所有标记分成每个点的显示方案
  - 分发到各个手机,保存到手机端,形成方案1 , 达到离线的目的
- [管理者] 提前发送显示命令到所有手机,以服务器端时间戳为开始时间,到时间显示
  - 比如,提前5分钟(18:25)发送, 定时到18:30开始运行方案1
  - 某个人的手机收到命令时获取的服务器时间是 18:28:50 ,  开始计时, 那么会在 70秒后开始运行 
  - 主要是为了保持同步
  - 如果网络信号有问题,未能收到命令,可以考虑手动运行方案1
就类似上面这样
如果现实,我不是特别懂..尤其是如何实现动画效果,不知道是否有类似的引擎或者库来实现
之所以不用实时的命令,是怕场地各种情况下,信号的问题

=======

不知道是不是有用

```
   *             *           *     * * 
   *  *****      *  *****    *     *   
   *     *     ****  *  *  **** ****** 
 *****  *        *   *  *    *  *  *   
   *   *         *  *  **    *  *  * * 
  **  ******  ******       **** * ** * 
  ***  * * *     *  *****    *  ** **  
 * * * * * *   * *  *   *  * *  *  * * 
   *  * *  *   * ****   *  * **   * ** 
   * *  *  *   * *  *****  * *   *   * 
   *   *   *   ***         ***         
   *  *  **   *  ********  * ********* 
```

```
　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　
　　　　。　　　　　　　　　　　　　　　　。　　　　　　　　　　　　　　。　　　　　　。　。　　　
　　　　。　　　。。。。。。　　　　　　　。　　。。。。。。。　　　　　。　　　　　　。　　。　　
　　　　。　　　　　　　。　　　　　　　　。　　　　。　　　。　　　　　。　　　　　　。　　　　　
　　　　。　　　　　　。　　　　　　。。。。。。　　。　　　。　　　。。。。。　。。。。。。。　　
　。。。。。。　　　。　　　　　　　　　　。　　　　。　　　。　　　　　。　　　。　　。　　　　　
　　　　。　　　　。　　　　　　　　　　　。　　　。　　。　。　　　　　。　　　。　　。　　。　　
　　　。。　　　。。。。。。。。　。。。。。。。。　　　　。　　　。。。。。。　。　　。　　。　　
　　　。。。　　　。　　。　　。　　　　　。　　　。。。。。。　　　　　。　　　。　　。　。　　　
　　。　。　。　　。　　。　　。　　　。　。　　　。　　　　。　　　　　。　　　。　　。　。　　　
　　。　。　。　　。　　。　　。　　　。　。　　　。　　　　。　　　。　。　　　。　　　。　　　　
　。　　。　　　。　　　。　　。　　　。　。。。　。　　　　。　　　。　。。。　。。　　。　。　　
　　　　。　　　。　　。　　　。　　　。　。　　　。。。。。。　　　。　。　　　。　　。　。。　　
　　　　。　　。　　　。　　　。　　　。　。　　　　　　　　　　　　。。。　　　　　。　　　。　　
　　　　。　。　　　。　　　　。　　。　。。　　　　　　　　　　　　。　。　　　　　　　　　　　　
　　　　。　　　　。　　。　。　　　。　　。。。。。。。。。。。　　。　　。。。。。。。。。。。　
　　　　。　　　。　　　　。　　　。　　　　　　　　　　　　　　　。　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　
```

**Comment by fishpisces** [comment]
> 　　　　。　　　。　　　　。　　　。　　　　　　　　　　　　　　　。　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　
> ```

明白……我的意思就是说手机面积上比灯牌小一些……当然从技术实现来说应该会比灯牌更简单、方便。

根据你的，我扩展下
【用户】直接输入座位号，后台根据座位号来排位，以防用户不知道点哪里，或者点错。也可提前根据座位号离线自己的方案。
【展现形式】我想的花里胡哨些。从静态文字变成动态画面。假设一次点阵为一帧，那就是从N秒一帧的静态字变成一秒N帧的跑马灯----->再花里胡哨点就组成个越哥的上半身动画了

其它的就项目组的同志考虑了。。。我就是作为个PM提点自己的意见-，-

话说项目发起人来看看啊~~~

**Comment by sxw228** [comment]
嵌入式开发方向的，有过LED点阵应用的开发经验，QQ 103312311

**Comment by QuartzYan** [comment]
上班时间不能一一回复，请大家先加群
欢迎加入杨超越灯牌计划，群聊号码：312166531

**Comment by QuartzYan** [comment]
# 杨超越灯牌计划比赛说明
## 1.前提
由于灯牌计划参与人数较多，且有多种实施方案，为方便后期实施，现将灯牌计划如何展开为群友做简要说明。
## 2.现已有方案
- 单灯牌方案
- 多灯牌联动方案
  
> *之后会出具详细的项目说明*

## 3.灯牌计划如何展开
由于灯牌项目有两种方案，故决定两方案同时上线，具体流程如下：
- 出具详细的项目说明文档
- 群友根据出具的项目说明文档，自由选择要参与的项目，并报名
- 3月12日比赛组队结束之前，各项目负责人筛选出合适的人选，正式开始比赛
- 比赛期间向群友汇报项目进展
- 比赛结束后根据实际情况，可开源各自项目

## 4.一些小要求
- 比赛期间请务必遵守：友谊第一，比赛第二
- 快乐追星，不要让比赛过多的影响自己的工作、学习或生活
- 项目中如用到第三方开源库，请根据其开源协议做必要说明

**Comment by QuartzYan** [comment]
由于该存储库更工作相关，故关闭此issue，相关讨论请移步至QQ群，或专属[存储库](https://github.com/QuartzYan/CYC_LightPlatePlan)
